# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the custom Nginx configuration file to the appropriate location
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to the outside world
EXPOSE 80
